# Настройки только для dev профиля
server:
  port: 8081  # другой порт для dev

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # in-memory БД для разработки
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    org.springframework: DEBUG
    com.example: TRACE
  file:
    name: logs/dev-app.log

app:
  debug: true
  feature-flags:
    new-ui: true
    experimental-api: false
