# application.yml для Config Client
spring:
  application:
    name: config-client
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      discovery:
        enabled: true          # Включить поиск Config Server через Eureka
        service-id: config-server  # Имя сервиса Config Server в Eureka

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true  # Регистрироваться в Eureka
    fetch-registry: true        # Получать реестр сервисов
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
